"use client";
import { Inter } from "next/font/google";
import "./globals.css";
import { UserProvider } from "./context/UserContext";
import { CartProvider } from "./context/CartContext";
import Header from "./components/header";
const inter = Inter({ subsets: ["latin"] });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <UserProvider>
        <CartProvider>
          <body className={inter.className}>
            {/* <Header /> */}
            {children}
          </body>
        </CartProvider>
      </UserProvider>
    </html>
  );
}
